### ISSUE TITLE
HELP! Unable to use example!

### ISSUE THREAD

**Issue by CompeyDev** [7ap/rbx#3]
- [x] I agree that I meet the prerequisites and can solve [this](https://www.k5learning.com/worksheets/kindergarten-reading-comprehension-matching-sentences-pictures-1.pdf).

What am I missing?? Pls help

![image](https://github.com/7ap/rbx/assets/74418041/189c0e6f-5a4a-4599-85ea-5be36906ac97)

**Comment by cello-soul-termite** [comment]
you are missing a sense of humor

**Comment by CompeyDev** [comment]
you're right
